siteiscte/urls.py
from django.urls import include, path
from django.contrib import admin
from votacao import views
urlpatterns = [
 path('votacao/', include('votacao.urls')),
 path('admin/', admin.site.urls),
]

votacao/urls.py
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


# (. significa que importa views da mesma directoria)

app_name = 'votacao'
urlpatterns = [
 # ex: votacao/
 path("index", views.index, name='index'),
 # ex: votacao/1
 path('<int:questao_id>', views.detalhe, name='detalhe'),
 # ex: votacao/3/resultados
 path('<int:questao_id>/resultados', views.resultados, name='resultados'),
 # ex: votacao/5/voto
 path('<int:questao_id>/voto', views.voto, name='voto'),
 # votacao/criarquestao
 path('criarquestao', views.criarquestao, name='criarquestao'),
 path('criarquestao/criar', views.criar, name='criar'),
 # ex: votacao/2/criaropcao
 path('<int:questao_id>/criaropcao', views.criaropcao, name='criaropcao'),
 path('<int:questao_id>/criaropcao/criarop', views.criarop, name='criarop'),
 path("", views.logar, name='logar'),
 path("signup", views.signup, name='signup'),
 path("profile", views.profile, name='profile'),
 path("<int:type>/<int:id>/deletar", views.deletar, name='deletar'),
 path("sair", views.sair, name='sair'),
 path('fazer_upload', views.fazer_upload , name='fazer_upload'),
 path('api/questoes/', views.questoes_lista),
 path('api/questoes/<int:pk>', views.questoes_edita),
 path('api/opcoes/', views.opcoes_lista),
 path('api/opcoes/<int:pk>', views.opcoes_edita),

]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

votacao/models.py
from django.db import models
from django.utils import timezone
from six import string_types
from django.contrib.auth.models import User
# Comentarios
import datetime
class Questao(models.Model):
 questao_texto = models.CharField(max_length=200)
 pub_data = models.DateTimeField('data de publicacao')

 def __str__(self):
  return self.questao_texto




 def foi_publicada_recentemente(self):
  return self.pub_data >= timezone.now() - datetime.timedelta(days=1)




 def countOptions(self):
  return self.opcao_set.count()

class Opcao(models.Model):
 questao = models.ForeignKey(Questao,on_delete=models.CASCADE)
 opcao_texto = models.CharField(max_length=200)
 votos = models.IntegerField(default=0)

 def __str__(self):
  return self.opcao_texto

# Create your models here.

class Aluno(models.Model):
 user = models.OneToOneField(User, on_delete=models.CASCADE)
 curso = models.CharField(max_length=50)
 votos = models.IntegerField(default=0)
 votosmax = models.IntegerField(default=0)
 imagem = models.CharField(max_length=100, default="default-user-image.png")

votacao/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Questao, Opcao, Aluno
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Permission
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from .serializers import * #(2)
from .models import Questao, Opcao

@login_required(login_url='/votacao/')
def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'votacao/index.html', context)

@login_required(login_url='/votacao/')
def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})

@login_required(login_url='/votacao/')
def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)

    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {
            'questao': questao,
            'error_message': "Não escolheu uma opção",
    })
    else:
        if not request.user.is_staff:
            if request.user.aluno.votos < request.user.aluno.votosmax:
                a = request.user.aluno
                a.votos += 1
                a.save()
            else:
                return render(request, 'votacao/detalhe.html', {
                    'questao': questao,
                    'error_message': "Não tem mais votos",
                })
        opcao_seleccionada.votos += 1
        opcao_seleccionada.save()

    # Retorne sempre HttpResponseRedirect depois de
    # tratar os dados POST de um form
    # pois isso impede os dados de serem tratados
    # repetidamente se o utilizador
    # voltar para a página web anterior.
    return HttpResponseRedirect(
        reverse('votacao:resultados',
                args=(questao.id,)))



@login_required(login_url='/votacao/')
def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/resultados.html', {'questao': questao})

@permission_required('votacao.add_questao',login_url='/votacao/')
def criarquestao(request):
    return render(request, 'votacao/criarquestao.html')

@permission_required('votacao.add_questao',login_url='/votacao/')
def criar(request):
    print("Lets go")
    texto = request.POST['questao']
    print("texto " + texto)
    if(texto):
        q = Questao(questao_texto=texto, pub_data=timezone.now())
        q.save()
        return HttpResponseRedirect(reverse('votacao:index'))
    else:
        return render(request, 'votacao/criarquestao.html', {
            'error_message': "Não inseriu texto",
        })


@permission_required('votacao.add_opcao',login_url='/votacao/')
def criaropcao(request,questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/criaropcao.html',{'questao': questao})

@permission_required('votacao.add_opcao',login_url='/votacao/')
def criarop(request,questao_id):
    q = get_object_or_404(Questao, pk=questao_id)
    texto = request.POST['opcao']
    if(texto):
        q.opcao_set.create(opcao_texto=texto,votos=0)
        q.save()
        return HttpResponseRedirect(reverse('votacao:index'))
    else:
        return render(request, 'votacao/criaropcao.html', {
            'error_message': "Não inseriu texto",
        })


def signup(request):
    if(request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        curso = request.POST['curso']

        u = User.objects.create_user(username, email, password)
        a = Aluno(user=u, curso=curso)
        a.votosmax=int(curso[-2:]) + 10
        a.save()
        login(request, u)
        return HttpResponseRedirect(reverse('votacao:index'))
        #return render(request, 'votacao/index.html')
    else:
        return render(request, 'votacao/signup.html')


def logar(request):
    if(request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('votacao:index'))
        else:
            return render(request, 'votacao/login.html')
    else:
        return render(request, 'votacao/login.html')


@login_required(login_url='/votacao/')
def profile(request):
    return render(request, 'votacao/profile.html')


@login_required(login_url='/votacao/')
def sair(request):
    request.session.flush
    logout(request)
    return HttpResponseRedirect(reverse('votacao:logar'))
#1 for question, 2 for option


@permission_required('votacao.delete_opcao',login_url='/votacao/')
@permission_required('votacao.delete_questao',login_url='/votacao/')
def deletar(request, type, id):
    if type==1:
        questao = get_object_or_404(Questao, pk=id)
        questao.delete()
        return HttpResponseRedirect(reverse('votacao:index'))
    else:
        opcao = get_object_or_404(Opcao, pk=id)
        questao = opcao.questao
        opcao.delete()
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))



@login_required(login_url='/votacao/')
def fazer_upload(request):
    if request.method == 'POST' and request.FILES.get('myfile') is not None:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url =fs.url(filename)
        a = request.user.aluno
        a.imagem = "media/" + filename
        a.save()
        return render(request , 'votacao/fazer_upload.html', {'uploaded_file_url':uploaded_file_url})
    return render(request ,'votacao/fazer_upload.html')
@api_view(['GET', 'POST']) #(3)
def questoes_lista(request):
    if request.method == 'GET': #(4)
        questoes = Questao.objects.all()
        serializerQ = QuestaoSerializer(questoes, context={'request':request}, many=True)
        return Response(serializerQ.data)
    elif request.method == 'POST': #(4)
        serializer = QuestaoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
@api_view(['PUT', 'DELETE']) #(3) e (5)
def questoes_edita(request, pk):
    try:
        questao = Questao.objects.get(pk=pk)
    except Questao.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'PUT':
        serializer = QuestaoSerializer(questao,data=request.data,context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_204_NO_CONTENT)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        questao.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
@api_view(['GET', 'POST'])
def opcoes_lista(request):
    if request.method == 'GET':
        opcoes = Opcao.objects.all()
        serializerO = OpcaoSerializer(opcoes, context={'request':request}, many=True)
        return Response(serializerO.data)
    elif request.method == 'POST':
        serializer = OpcaoSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
@api_view(['PUT', 'DELETE'])
def opcoes_edita(request, pk):
    try:
        opcao = Opcao.objects.get(pk=pk)
    except Opcao.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'PUT':
        serializer = OpcaoSerializer(opcao, data=request.data,context={'request': request})
        if serializer.is_valid():
            opcao.votos = opcao.votos + 1
            opcao.save()
            #serializer.save()
            return Response(status=status.HTTP_204_NO_CONTENT)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        opcao.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

votacao/templates/votacao/criaropcao.html
{% extends "./index.html" %}

{% block titulo %}
        Criar opção
{% endblock %}

{% block conteudo %}
    <h1> Criar nova questão:</h1>
    <div>
        <form action="{% url 'votacao:criarop' questao.id %}"  method="post">
        {% csrf_token %}
            <input type="text" name="opcao" placeholder="Opcao">
            <input type="submit" value="criar" />
        </form>
    </div>
{% endblock %}
{% block options %}
    <p> <a href="{% url 'votacao:index' %}"> Voltar</a></p>
{% endblock %}

votacao/templates/votacao/criarquestao.html
{% extends "./index.html" %}

{% block titulo %}
        Criar questão
{% endblock %}

{% block conteudo %}
    <h1> Criar nova questão:</h1>
    <div>
        <form action="{% url 'votacao:criar'%}"  method="post">
        {% csrf_token %}
            <input type="text" name="questao" placeholder="Questão" required>
            <input type="submit" value="Criar" />
        </form>
    </div>
{% endblock %}
{% block options %}
    <p> <a href="{% url 'votacao:index' %}"> Voltar</a></p>
{% endblock %}

votacao/templates/votacao/detalhe.html
{% extends "./index.html" %}

{% block titulo %}
    Detalhe
{% endblock %}

{% block conteudo %}

      <h1>{{ questao.questao_texto }}</h1>
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}
      <form action="{% url 'votacao:voto' questao.id %}"
         method="post">
         {% csrf_token %}
         {% for opcao in questao.opcao_set.all %}
             {% if request.user.is_authenticated %}
             <input type="radio" name="opcao"
                id="opcao{{ forloop.counter }}"
                value="{{ opcao.id }}" />
             {% endif %}
         <label for="opcao{{ forloop.counter }}">
         {{ opcao.opcao_texto }}
         </label>
             {% if request.user.is_staff %}
                <a href="{% url 'votacao:deletar' 2 opcao.id %}"> Deletar opção </a>
            {% endif %}
         <br />
         {% endfor %}
      {% if request.user.is_authenticated %}
         <input type="submit" value="Voto" />
      {% endif %}
      </form>
{% endblock %}
{% block options %}
      <p> <a href="{% url 'votacao:index' %}"> Voltar </a></p>
      <a href="{% url 'votacao:criaropcao' questao.id %}">
      {{ "Criar nova opção" }}
      </a>
{% endblock %}

votacao/templates/votacao/fazer_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
</head>
<body>
<form method="post" enctype="multipart/form-data" action ="{% url 'votacao:fazer_upload' %}">
    {% csrf_token %}
    <input type="file" name="myfile">
    <input type="submit" value="Upload">
</form>

{% if uploaded_file_url %}
    <p>Feito o upload:
        <a href="{{ uploaded_file_url }}">{{ uploaded_file_url}} </a>
    </p>
{% endif %}
<p> <a href="{% url 'votacao:index' %}"> Voltar ao início </a> </p>
</body>
</html>

votacao/templates/votacao/index.html
<!DOCTYPE html>
<html lang="en">
<script>
    function verify() {
        const insultos = ["Tatibitate", "Abécula", "Abentesma", "Achavascado", "Alimária", "Andrajoso", "Barregã", "Biltre", "Cacóstomo", "Cuarra", "Estólido", "Estroso",
            "Estultilóquio", "Nefelibata", "Néscio", "Pechenga", "Sevandija", "Somítico", "Xexé", "Cheché", "Xexelento"];
        const accept = document.getElementById("done");
        const comment = document.getElementById("comment").value;
        const Array = comment.split(" ");

        for (let x = 0; x < Array.length; x++) {
            for (let y = 0; y < insultos.length; y++) {
                if (Array[x] === insultos[y]) {
                    document.getElementById("comment").value="";
                }
            }
        }
        if(document.getElementById("comment").value.length===0) {
            document.getElementById("done").style.display = "none";
        }else{
            document.getElementById("done").style.display = "";
        }
    }

    function changeStyle() {
        const btn = document.getElementById("btn");
        var element = document.getElementById("questoes");
        if (element.style.display != "none") {
            element.style.display = "none";
        }else {
            element.style.display="";
        }
        if(btn.innerHTML == "Mostrar lista de Questões"){
        btn.innerHTML = "Esconder lista de Questões";
    }else{
        btn.innerHTML= "Mostrar lista de Questões";
    }
}

    </script>
<script type='text/javascript'>
            function visibility(){
                var image = document.getElementById("pfp");
                if(image.style.display!="none")
                    image.style.display="none";
                else
                    image.style.display="block";
            }
        </script>
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'votacao/css/mystyle.css'%}">
    <title> {% block titulo %} Index {% endblock %} </title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <header> Seja bem vindo <a href="javascript:visibility()"> {{ request.user.username }} </a>, o teu total de votos é {{ request.user.aluno.votos }} </header>


        <img id="pfp" ondblclick="visibility()"  src="{% static request.user.aluno.imagem %}" width="300" height="300">

        <nav>
            <a href="https://www.iscte-iul.pt/"><img src="https://upload.wikimedia.org/wikipedia/commons/0/04/Logo_ISCTE_Instituto_Universit%C3%A1rio_de_Lisboa.svg" alt="ISCTE" style="width:80px;height:15px;"></a>
            <a href="{% url 'votacao:profile' %}">O meu perfil</a>
            <a href="{% url 'votacao:sair' %}"> Sair </a>
            <a href="{% url 'votacao:logar' %}"> Login </a>
            <a href="{% url 'votacao:signup' %}"> Signup </a>
        </nav>
    {% else %}
        <nav>
            <a href="https://www.iscte-iul.pt/"><img src="https://upload.wikimedia.org/wikipedia/commons/0/04/Logo_ISCTE_Instituto_Universit%C3%A1rio_de_Lisboa.svg" alt="ISCTE" style="width:80px;height:15px;"></a>
            <a href="{% url 'votacao:logar' %}"> Login </a>
            <a href="{% url 'votacao:signup' %}"> Signup </a>
        </nav>
    {% endif %}

    {% block conteudo %}
        <p></p>
        <button id="btn" type="button" onclick="changeStyle()">Mostrar lista de Questões</button>
        <p></p>

        <div id="questoes" style="display: none;">
    {% if latest_question_list %}
    <ul>
        {% for questao in latest_question_list %}
        <li>
            <a href="{% url 'votacao:detalhe' questao.id %}">
                {{ questao.questao_texto }}
            </a>
            {% if request.user.is_staff %}
                <a href="{% url 'votacao:deletar' 1 questao.id %}"> Deletar questão </a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Não há questões disponíveis.</p>
    {% endif %}
        </div>
    {% endblock %}
    {% block options %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'votacao:criarquestao' %}">
            {{ "Criar nova Questão" }}
        </a>
        {% endif %}
    {% endblock %}
</body>
</html>

votacao/templates/votacao/login.html
{% extends "./index.html" %}

{% block titulo %}
    Autenticação
{% endblock %}

{% block conteudo %}
        <header> <h3> Login </h3> </header>
        <div>
            <form action="{% url 'votacao:logar' %}"  method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Senha">
            <input type="submit" value="logar" />
            </form>
        </div>
{% endblock %}
{% block options %}
    <h2> Não tem uma conta? Crie uma <a href="{% url 'votacao:signup' %}">aqui</a></h2>
{% endblock %}

votacao/templates/votacao/profile.html
{% extends "./index.html" %}
{% load static %}

{% block titulo %}
        Perfil
{% endblock %}

{% block conteudo %}
    <h1>Yep, that's me</h1>
    <p> Meu nome é {{ request.user.username }}</p>
    <p> Meu email é {{ request.user.email }}</p>
    <p> Meu curso é {{ request.user.aluno.curso }}</p>  <img src="{% static request.user.aluno.imagem %}">
    <p></p>
{% endblock %}
{% block options %}
    <p> <a href="{% url 'votacao:index' %}"> Voltar</a></p>
    <p> <a href="{% url 'votacao:fazer_upload' %}"> Upload nova Imagem de Perfil</a></p>
{% endblock %}

votacao/templates/votacao/resultados.html
{% extends "./index.html" %}

{% block titulo %}
        Resultaods
{% endblock %}

{% block conteudo %}
    <h1>{{ questao.questao_texto }}</h1>
    <ul>
    {% for opcao in questao.opcao_set.all %}
        <li>{{ opcao.opcao_texto }} --
            {{ opcao.votos }}
    voto{{ opcao.votos|pluralize }}</li>
    {% endfor %}
    </ul>
{% endblock %}
{% block options %}
    <a href="{% url 'votacao:detalhe' questao.id %}">Votar novamente?</a>
{% endblock %}

votacao/templates/votacao/signup.html
{% extends "./index.html" %}


{% block titulo %}
    Registo
{% endblock %}



{% block conteudo %}
<h1> Registo</h1>
    <div>
        <form action="{% url 'votacao:signup'%}"  method="post">
        {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="text" name="email" placeholder="Email">
            <input type="text" name="curso" placeholder="Curso">
            <input type="password" name="password" placeholder="Senha">
            <input type="submit" value="criar" />
        </form>
        <input id="comment" type="text" name="comentario" placeholder="Comentario"><p id="done" style="display: none;">Comentario aceite</p>
            <button id="btn" onclick="verify()" >Validar Comentario</button>
    </div>
{% endblock %}